export enum EVENT_IMPLEMENTOR_TYPE_IDS {
    NODE_CHANGE = 1,
    NODE_FRAGMENT_CHANGE = 2,
    LINK_CHANGE = 3
}

export enum EVENT_IMPLEMENTOR_TYPE_NAMES {
    NODE_CHANGE = 'NODE_CHANGE',
    NODE_FRAGMENT_CHANGE = 'NODE_FRAGMENT_CHANGE',
    LINK_CHANGE = 'LINK_CHANGE'
}
